FROM trion/ng-cli:latest as build
WORKDIR /app
COPY ./src ./src
COPY ./angular.json ./angular.json
COPY ./karma.conf.js ./karma.conf.js
COPY ./package.json ./package.json
COPY ./tsconfig.app.json ./tsconfig.app.json
COPY ./tsconfig.json ./tsconfig.json
COPY ./tsconfig.spec.json ./tsconfig.spec.json

RUN npm install
RUN npm run build:prod

FROM nginx:alpine
COPY --from=build /app/dist/bookstore-frontend /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80